### ISSUE TITLE
Wrong Data Format

### ISSUE THREAD

**Issue by BB1464** [DSSAT/dssat-csm-data#106]
Good Day Dear All,
    While looking at the data format in the latest version of DSSAT (4.8.2) Example cassava module, the file X (CCPA7801.CSX) and some other files in there does not come in the right format, I am viewing the files on a windows computer (windows 10). Please can this be updated. Thanks

**Comment by fabiooliveira72** [comment]
Hi @BB1464!

Please give us more information about this. Note that CCPA7801.CHX.CSX is not in the repository. If you have this file. It is wrong.

Is it related to the DSSAT installed in your machine? If so please use https://dssat.net/contact-us

Thank you

**Comment by BB1464** [comment]
Thanks @fabiooliveira72 for the response, if you can confirm at your own end when you want to manually edit that file it will fail because of the format, but this works fine for other files. Here is a screenshot. I will contact the DSSAT team as you suggested!!!

![2023-11-09](https://github.com/DSSAT/dssat-csm-data/assets/76583394/5c867071-61d8-45ab-96a7-2a94cffd639d)

![2023-11-09 (1)](https://github.com/DSSAT/dssat-csm-data/assets/76583394/37be60e8-aa52-4a97-8e91-48f029a66ec0)

**Comment by BB1464** [comment]
There was a typo in my original post, I have corrected it

**Comment by fabiooliveira72** [comment]
Hi @BB1464 

Please let me know which version of DSSAT you are using. Is it from the DSSAT training workshop?

Thank you.

Fabio Oliveira

**Comment by BB1464** [comment]
Thanks @fabiooliveira72, I am using the latest version of DSSAT (version 4.8.2.0) and it is from the training workshop. I just discovered this issue today!!!

**Comment by fabiooliveira72** [comment]
Hi @BB1464!

Please uninstall completely this version and download again in dssat.net webpage the latest version. Follow the instructions there.

Next questions send through there too.

Thank you.

Fabio Oliveira
