### ISSUE TITLE
How to modify DSSATPRO.v47 for relative paths in Windows

### ISSUE THREAD

**Issue by helsharif** [DSSAT/dssat-csm-data#43]
Hello, I am trying to run DSSAT from any folder of choice, so I wanted to modify the DSSATPRO.v47 file so that relative paths are used.

I followed the procedure of replacing "C:" with ". " (period+space), and removed "\DSSAT47" 

However when I try to run the command in PowerShell (Command Prompt)

.\DSCSM047 A UFGA8201.MZX

The UFGA8201.MZX file is not found, even though it is located in the Maize subdirectory. If I move the MZX file to the same directory as the executable the DSSAT code runs properly. 

I'm guessing I did not modify the DSSATPRO.v47 correctly, but I can't figure out what I did wrong. 

I'm attaching the modified DSSATPRO.v47 file (added a .txt extension to allow for attachment)
[DSSATPRO.v47.txt](https://github.com/DSSAT/dssat-csm-data/files/7610831/DSSATPRO.v47.txt)
.

**Comment by frostbytten** [comment]
You can execute DSSAT in any folder if it is on the path. The DSSATPRO file is used as a "if any files are missing in the current directory, use this path" default. This should be the installation directory (typically C:\DSSAT47). You can also call using the full path (again with the default DSSATPRO file) with the same mechanics. As long as your current working directory has DSSAT files, it will use those first.

**Comment by helsharif** [comment]
Thank you for your reply, I understand what you're saying, but I am trying to run DSSAT without being limited to using C:\DSSAT47

By modifying the DSSATPRO file I'm able to successfully get DSSAT to see the StandardData, Soil, and Genotype folders; however, I am unable to get the DSSAT executable to see any of the crop folders (e.g. \Maize) even though I used the same approach of changing C: to ". " and removing "\DSSAT47"

Here is a screenshot of how I have the folder setup. The only way so far for dssat to see the UFGA8201.MZX file is if it is in the same directory as the executable. But I really would like to keep it in the \Maize folder. 
![image](https://user-images.githubusercontent.com/14345478/143660539-68dbe02f-528c-4a22-8117-a867b1b9f261.png)

**Comment by frostbytten** [comment]
I guess the question I have is: What is the goal of what you are attempting to do?

 Putting the full path (E: \Final) in DSSATPRO accomplishes the same thing. The crop directories actually only hold experiments that are shipped and have nothing to do (directly) with parameters or cultivars. The only way they are executed is by cd'ing to the crop directory and executing dscsm047 in that directory.

 If you attempt to make everything relative to your current directory, every directory you would want to work in would need StandardData, Genotype and Cultivar files (or folders).

**Comment by helsharif** [comment]
My goal is to run DSSAT in a way that is as portable as possible. I would like for example to be able to copy this directory (called 'FINAL' in this case), to any folder or any other windows system and be able to run DSSAT. I would also like to keep the contents of the 'FINAL' folder organized such that the FileX files (e.g. UFGA8201.MZX) can stay in their respective crop folders. 

My understanding was that by modifying the DSSATPRO.v47 file, the dssat executable will be directed to look in the proper folders (using relative paths) and find the necessary files it needs to run. 

With my current modifications to DSSATPRO.v47 the executable is able to find all the files it needs except the FileX. I'm not sure what I did wrong. 

This screenshot shows an excerpt of my modified DSSATPRO.47. 
![image](https://user-images.githubusercontent.com/14345478/143663904-ce3b98a0-6b44-4f17-9e91-045093b3a3de.png)


But even though line 138 reads:
MZD .  \Maize

When I run the command (with Powershell open in the E:/FINAL directory):

.\DSCSM047 A UFGA8201.MZX

DSSAT says the FileX cannot be found:

![image](https://user-images.githubusercontent.com/14345478/143663929-7c176d34-a247-4e24-a797-69e8db8d0a57.png)

Even more strange is if I make line 138 point to the absolute path, for example:
MZD E: \FINAL\Maize

I get the same error. It seems that I can't get the executable to look into any of the crop directories.

**Comment by fabiooliveira72** [comment]
HI @helsharif!

The DSSAT is built to go default for C: drive. If you want this relative directory you need to create this "FINAL" directory and place all the files in the same level ( Soil, weather, StandardData, Genotype and Cultivar and experiments, etc). In the DSSATPRO.v47 I would put ".."and not only "." because fortran use fixed form, I am not sure now if this could be and issue. Then you can ran in the same directory and move the directory. If not you need to have and environmental variables to say where is the DSSATPRO.v47 called DSSAT_HOME.

Thank you.

Fabio Oliveira
